apiVersion: v1
kind: Service
metadata:
  name: grpcbin
spec:
  clusterIP: None
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: grpcbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcbin
  labels:
    app: grpcbin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpcbin
  template:
    metadata:
      labels:
        app: grpcbin
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: app
          image: moul/grpcbin
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: 50Mi
              cpu: "1"
            limits:
              memory: 50Mi
              cpu: "1"
