apiVersion: v1
kind: Service
metadata:
  name: echo-server
spec:
  clusterIP: None # 使用 Headless Service
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: echo-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  labels:
    app: echo-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: app
          image: test/load_balancing_test:latest
          ports:
            - containerPort: 9000
          command: ["./echo_server"]
